name: Build RU Rules

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build geodata
        run: |
          wget https://github.com/urunsayan/v2dat/releases/latest/download/v2dat-linux-amd64.tar.gz
          tar -xf v2dat-linux-amd64.tar.gz
          chmod +x v2dat

          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -O full_geosite.dat
          ./v2dat unpack geosite -o ./geosite_dir -f ru -f category-ads-all -f private full_geosite.dat
          ./v2dat pack geosite -o . ./geosite_dir
          mv geosite.dat geosite.dat

          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -O full_geoip.dat
          ./v2dat unpack geoip -o ./geoip_dir -f ru -f private full_geoip.dat
          ./v2dat pack geoip -o . ./geoip_dir
          mv geoip.dat geoip.dat

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: RU Rules
          files: |
            geosite.dat
            geoip.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
